### ISSUE TITLE
[HyBox/production] ActiveModel::UnknownAttributeError: unknown attribute 'workflow_id' for Hyrax::PermissionTemplate.

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#843] opened 2017-03-02 22:56 UTC
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32845399)

**Comment by laritakr** [comment] 2017-03-15 16:28
Duplicate of issue https://github.com/projecthydra-labs/hyku/issues/853, fixed by https://github.com/projecthydra-labs/hyrax/pull/549

**Closed by laritakr** 2017-03-15 16:28 UTC
Labels: exception
