### ISSUE TITLE
[HyBox/production] PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#670] opened 2017-01-25 00:01 UTC
## Backtrace

    line 5 of [PROJECT_ROOT]/config/environment.rb: <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32436001)

**Comment by atz** [comment] 2017-01-25 02:26
Duplicate of #669

**Closed by atz** 2017-01-25 02:26 UTC
Labels: exception
