### ISSUE TITLE
original file name is not preserved and displayed

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#1021] opened 2017-04-28 17:53 UTC
After a file upload is complete, I can see the original file name on the screen (in this case, it is 507003680.jpg).

![screenshot 2017-04-28 10 49 53](https://cloud.githubusercontent.com/assets/1801076/25540743/025f55ec-2c01-11e7-913d-3d68a0e86b5b.png)

But after I submit the work, there is no trace of the original file name. If it is being stored with the work, it is not displayed to the user. The file is only ever displayed or available for download with its associated AWS-assigned string.

![screenshot 2017-04-28 10 51 57](https://cloud.githubusercontent.com/assets/1801076/25540736/fb4d9728-2c00-11e7-8beb-fdac9502a58b.png)

**Comment by mjgiarlo** [comment] 2017-04-28 18:22
:+1: I can confirm this as well. FileSet titles appear to get set to a Fedora UUID with '20170428-25491-1qwnver' (an S3 string?) appended.

**Comment by mjgiarlo** [comment] 2017-04-28 18:23
@hannahfrost When you browse to this work's show page, do you see the metadata you entered for it (keywords, rights, creator)?

**Comment by hannahfrost** [comment] 2017-04-28 19:04
@mjgiarlo no, I do not, and was just about to enter that ticket too.

**Comment by atz** [comment] 2017-04-28 20:04
@mjgiarlo: the `20170428...` is at least partially datestamp based.  Wouldn't be surprised if the `1qwnver` was some kind of checksum.

**Comment by mjgiarlo** [comment] 2017-05-08 19:32
I can't reproduce this locally. Appears to be AWS deployment-specific (likely due to carrierwave-aws?).

**Comment by mjgiarlo** [comment] 2017-05-08 22:59
OK, found a way to reproduce this locally. Have a fix close to ready.

**Comment by mjgiarlo** [comment] 2017-05-09 22:44
Fix has been submitted for review.

**Closed** 2017-05-10 19:07 UTC
Labels: bug, in progress
