### ISSUE TITLE
download file is not working as expected

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#1024] opened 2017-04-28 19:44 UTC
When I click "download", the file loads in a browser window. Download to my local system does not start by itself after clicking a "download" link as one would expect.

On Chrome 58 and Safari 10.1

**Comment by jcoyne** [comment] 2017-04-28 19:53
Duplicate of https://github.com/projecthydra-labs/hyrax/issues/598 ?

**Comment by mjgiarlo** [comment] 2017-05-02 21:02
Yes, I believe this is a dup.

**Closed by mjgiarlo** 2017-05-02 21:02 UTC
Labels: bug, HyBox ready
