### ISSUE TITLE
[HyBox/production] ArgumentError: invalid date

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#503] opened 2016-12-02 14:59 UTC
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/31910428)

**Comment by tdonohue** [comment] 2016-12-02 15:18
I don't have access to honeybadger.io, but this sounds like a duplicate of https://github.com/projecthydra/curation_concerns/issues/1115

**Comment by mjgiarlo** [comment] 2016-12-02 15:22
I suspect you're right, @tdonohue. Thanks for making the linkage! (Do you want access to honeybadger?)

**Closed** 2017-02-06 20:10 UTC
Labels: exception
