### ISSUE TITLE
default permissions for admin set creator

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#549] opened 2016-12-16 15:45 UTC
As the creator of an admin set, I need permissions to deposit to the admin set by default

**Comment by mjgiarlo** [comment] 2016-12-16 16:34
Sounds like a bug.

**Comment by jcoyne** [comment] 2016-12-16 17:11
It's not a bug.  It's a feature that has never been requested until now.

**Comment by mjgiarlo** [comment] 2016-12-16 17:13
Is it? I've put works into admin sets a bunch of times. (As an administrator.)

**Comment by jcoyne** [comment] 2016-12-16 17:14
But you added yourself as a depositor first, right?

**Comment by mjgiarlo** [comment] 2016-12-16 17:15
@jcoyne No, I've never used that functionality.

**Comment by jcoyne** [comment] 2016-12-16 17:18
@mjgiarlo I don't understand how that possibly worked given the list of options comes from here: https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/admin_set_service.rb#L41

**Comment by mjgiarlo** [comment] 2016-12-16 17:23
@jcoyne we've used it a ton for mediated deposit sprints, because for some time that was the only way to see one-step workflow working. I haven't tried it with Hyrax yet, just Sufia.

Right, @vantuyls?

**Comment by jcoyne** [comment] 2016-12-16 17:26
@mjgiarlo it's the same code (more or less) in Sufia: https://github.com/projecthydra/sufia/blob/master/app/views/curation_concerns/base/_form_relationships.html.erb#L3

**Comment by mjgiarlo** [comment] 2016-12-16 17:54
You've got me. @vantuyls @scholarworks you've been able to deposit works into admin sets in the UI since Oct. 31 using Sufia, right?

**Comment by mjgiarlo** [comment] 2016-12-16 23:14
@jcoyne Should this have been auto-closed by https://github.com/projecthydra-labs/hyrax/pull/54 ?

**Comment by jcoyne** [comment] 2016-12-17 01:48
yes

**Closed by jcoyne** 2016-12-17 01:48 UTC
Labels: in progress
